import type { TokenDef, TokenSet } from './types'

export const tokenDefs: TokenDef[] = [
  // 표면(배경)
  { key: '--background', label: 'token.background', category: 'surface' },
  { key: '--card', label: 'token.card', category: 'surface' },
  { key: '--popover', label: 'token.popover', category: 'surface' },
  {
    key: '--muted',
    label: 'token.muted',
    category: 'surface',
    deriveFrom: { anchor: '--background', transform: 'mute-bg' },
  },
  {
    key: '--accent',
    label: 'token.accent',
    category: 'surface',
    deriveFrom: { anchor: '--background', transform: 'mute-bg' },
  },

  // 텍스트
  {
    key: '--foreground',
    label: 'token.foreground',
    category: 'text',
    contrastWith: '--background',
  },
  {
    key: '--card-foreground',
    label: 'token.cardForeground',
    category: 'text',
    contrastWith: '--card',
    deriveFrom: { anchor: '--card', transform: 'foreground' },
  },
  {
    key: '--popover-foreground',
    label: 'token.popoverForeground',
    category: 'text',
    contrastWith: '--popover',
    deriveFrom: { anchor: '--popover', transform: 'foreground' },
  },
  {
    key: '--muted-foreground',
    label: 'token.mutedForeground',
    category: 'text',
    contrastWith: '--muted',
  },
  {
    key: '--accent-foreground',
    label: 'token.accentForeground',
    category: 'text',
    contrastWith: '--accent',
    deriveFrom: { anchor: '--accent', transform: 'foreground' },
  },

  // 테두리/링
  { key: '--border', label: 'token.border', category: 'border' },
  { key: '--input', label: 'token.input', category: 'border' },
  {
    key: '--ring',
    label: 'token.ring',
    category: 'border',
    deriveFrom: { anchor: '--primary', transform: 'same' },
  },

  // 주색상
  { key: '--primary', label: 'token.primary', category: 'primary' },
  {
    key: '--primary-foreground',
    label: 'token.primaryForeground',
    category: 'primary',
    contrastWith: '--primary',
    deriveFrom: { anchor: '--primary', transform: 'foreground' },
  },

  // 보조
  { key: '--secondary', label: 'token.secondary', category: 'secondary' },
  {
    key: '--secondary-foreground',
    label: 'token.secondaryForeground',
    category: 'secondary',
    contrastWith: '--secondary',
    deriveFrom: { anchor: '--secondary', transform: 'foreground' },
  },

  // 피드백
  { key: '--destructive', label: 'token.destructive', category: 'feedback' },
  {
    key: '--destructive-foreground',
    label: 'token.destructiveForeground',
    category: 'feedback',
    contrastWith: '--destructive',
    deriveFrom: { anchor: '--destructive', transform: 'foreground' },
  },
  { key: '--success', label: 'token.success', category: 'feedback' },
  {
    key: '--success-foreground',
    label: 'token.successForeground',
    category: 'feedback',
    contrastWith: '--success',
    deriveFrom: { anchor: '--success', transform: 'foreground' },
  },
  { key: '--warning', label: 'token.warning', category: 'feedback' },
  {
    key: '--warning-foreground',
    label: 'token.warningForeground',
    category: 'feedback',
    contrastWith: '--warning',
    deriveFrom: { anchor: '--warning', transform: 'foreground' },
  },

  // 차트
  { key: '--chart-1', label: 'token.chart1', category: 'chart' },
  { key: '--chart-2', label: 'token.chart2', category: 'chart' },
  { key: '--chart-3', label: 'token.chart3', category: 'chart' },
  { key: '--chart-4', label: 'token.chart4', category: 'chart' },
  { key: '--chart-5', label: 'token.chart5', category: 'chart' },

  // 사이드바
  { key: '--sidebar', label: 'token.sidebar', category: 'sidebar' },
  {
    key: '--sidebar-foreground',
    label: 'token.sidebarForeground',
    category: 'sidebar',
    contrastWith: '--sidebar',
    deriveFrom: { anchor: '--sidebar', transform: 'foreground' },
  },
  {
    key: '--sidebar-primary',
    label: 'token.sidebarPrimary',
    category: 'sidebar',
    deriveFrom: { anchor: '--primary', transform: 'same' },
  },
  {
    key: '--sidebar-primary-foreground',
    label: 'token.sidebarPrimaryForeground',
    category: 'sidebar',
    contrastWith: '--sidebar-primary',
    deriveFrom: { anchor: '--sidebar-primary', transform: 'foreground' },
  },
  { key: '--sidebar-accent', label: 'token.sidebarAccent', category: 'sidebar' },
  {
    key: '--sidebar-accent-foreground',
    label: 'token.sidebarAccentForeground',
    category: 'sidebar',
    contrastWith: '--sidebar-accent',
    deriveFrom: { anchor: '--sidebar-accent', transform: 'foreground' },
  },
  { key: '--sidebar-border', label: 'token.sidebarBorder', category: 'sidebar' },
  {
    key: '--sidebar-ring',
    label: 'token.sidebarRing',
    category: 'sidebar',
    deriveFrom: { anchor: '--sidebar-primary', transform: 'same' },
  },

  // 헤더
  { key: '--header', label: 'token.header', category: 'header' },
  {
    key: '--header-foreground',
    label: 'token.headerForeground',
    category: 'header',
    contrastWith: '--header',
    deriveFrom: { anchor: '--header', transform: 'foreground' },
  },
  {
    key: '--header-border',
    label: 'token.headerBorder',
    category: 'header',
    deriveFrom: { anchor: '--border', transform: 'same' },
  },

  // 테이블/그리드
  { key: '--table-header', label: 'token.tableHeader', category: 'table' },
  {
    key: '--table-header-foreground',
    label: 'token.tableHeaderForeground',
    category: 'table',
    contrastWith: '--table-header',
  },
  { key: '--table-row', label: 'token.tableRow', category: 'table' },
  {
    key: '--table-row-foreground',
    label: 'token.tableRowForeground',
    category: 'table',
    contrastWith: '--table-row',
    deriveFrom: { anchor: '--table-row', transform: 'foreground' },
  },
  { key: '--table-row-hover', label: 'token.tableRowHover', category: 'table' },
  { key: '--table-row-selected', label: 'token.tableRowSelected', category: 'table' },
  { key: '--table-row-stripe', label: 'token.tableRowStripe', category: 'table' },
  {
    key: '--table-border',
    label: 'token.tableBorder',
    category: 'table',
    deriveFrom: { anchor: '--border', transform: 'same' },
  },
  { key: '--table-font-size', label: 'token.tableFontSize', category: 'table', kind: 'length' },
  { key: '--table-row-height', label: 'token.tableRowHeight', category: 'table', kind: 'length' },

  // 형태
  { key: '--radius', label: 'token.radius', category: 'shape', kind: 'length' },
]

// src/index.css의 초기값 (동기화 필수)
export const defaultTokens: TokenSet = {
  light: {
    '--background': 'oklch(1 0 0)',
    '--foreground': 'oklch(0.145 0 0)',
    '--card': 'oklch(1 0 0)',
    '--card-foreground': 'oklch(0.145 0 0)',
    '--popover': 'oklch(1 0 0)',
    '--popover-foreground': 'oklch(0.145 0 0)',
    '--primary': 'oklch(0.488 0.243 264.376)',
    '--primary-foreground': 'oklch(0.97 0.014 254.604)',
    '--secondary': 'oklch(0.967 0.001 286.375)',
    '--secondary-foreground': 'oklch(0.21 0.006 285.885)',
    '--muted': 'oklch(0.97 0 0)',
    '--muted-foreground': 'oklch(0.556 0 0)',
    '--accent': 'oklch(0.97 0 0)',
    '--accent-foreground': 'oklch(0.205 0 0)',
    '--destructive': 'oklch(0.577 0.245 27.325)',
    '--destructive-foreground': 'oklch(0.985 0 0)',
    '--success': 'oklch(0.627 0.194 142.5)',
    '--success-foreground': 'oklch(0.985 0 0)',
    '--warning': 'oklch(0.75 0.183 70)',
    '--warning-foreground': 'oklch(0.15 0 0)',
    '--border': 'oklch(0.922 0 0)',
    '--input': 'oklch(0.922 0 0)',
    '--ring': 'oklch(0.708 0 0)',
    '--chart-1': 'oklch(0.809 0.105 251.813)',
    '--chart-2': 'oklch(0.623 0.214 259.815)',
    '--chart-3': 'oklch(0.546 0.245 262.881)',
    '--chart-4': 'oklch(0.488 0.243 264.376)',
    '--chart-5': 'oklch(0.424 0.199 265.638)',
    '--sidebar': 'oklch(0.985 0 0)',
    '--sidebar-foreground': 'oklch(0.145 0 0)',
    '--sidebar-primary': 'oklch(0.546 0.245 262.881)',
    '--sidebar-primary-foreground': 'oklch(0.97 0.014 254.604)',
    '--sidebar-accent': 'oklch(0.97 0 0)',
    '--sidebar-accent-foreground': 'oklch(0.205 0 0)',
    '--sidebar-border': 'oklch(0.922 0 0)',
    '--sidebar-ring': 'oklch(0.708 0 0)',
    '--header': 'oklch(1 0 0)',
    '--header-foreground': 'oklch(0.145 0 0)',
    '--header-border': 'oklch(0.922 0 0)',
    '--table-header': 'oklch(0.97 0 0)',
    '--table-header-foreground': 'oklch(0.556 0 0)',
    '--table-row': 'oklch(1 0 0)',
    '--table-row-foreground': 'oklch(0.145 0 0)',
    '--table-row-hover': 'oklch(0.95 0 0)',
    '--table-row-selected': 'oklch(0.93 0.03 264.376)',
    '--table-row-stripe': 'oklch(0.985 0 0)',
    '--table-border': 'oklch(0.922 0 0)',
    '--table-font-size': '0.75rem',
    '--table-row-height': '1.75rem',
    '--radius': '0.45rem',
  },
  dark: {
    '--background': 'oklch(0.145 0 0)',
    '--foreground': 'oklch(0.985 0 0)',
    '--card': 'oklch(0.205 0 0)',
    '--card-foreground': 'oklch(0.985 0 0)',
    '--popover': 'oklch(0.205 0 0)',
    '--popover-foreground': 'oklch(0.985 0 0)',
    '--primary': 'oklch(0.424 0.199 265.638)',
    '--primary-foreground': 'oklch(0.97 0.014 254.604)',
    '--secondary': 'oklch(0.274 0.006 286.033)',
    '--secondary-foreground': 'oklch(0.985 0 0)',
    '--muted': 'oklch(0.269 0 0)',
    '--muted-foreground': 'oklch(0.708 0 0)',
    '--accent': 'oklch(0.269 0 0)',
    '--accent-foreground': 'oklch(0.985 0 0)',
    '--destructive': 'oklch(0.704 0.191 22.216)',
    '--destructive-foreground': 'oklch(0.985 0 0)',
    '--success': 'oklch(0.627 0.194 142.5)',
    '--success-foreground': 'oklch(0.985 0 0)',
    '--warning': 'oklch(0.75 0.183 70)',
    '--warning-foreground': 'oklch(0.15 0 0)',
    '--border': 'oklch(1 0 0 / 10%)',
    '--input': 'oklch(1 0 0 / 15%)',
    '--ring': 'oklch(0.556 0 0)',
    '--chart-1': 'oklch(0.809 0.105 251.813)',
    '--chart-2': 'oklch(0.623 0.214 259.815)',
    '--chart-3': 'oklch(0.546 0.245 262.881)',
    '--chart-4': 'oklch(0.488 0.243 264.376)',
    '--chart-5': 'oklch(0.424 0.199 265.638)',
    '--sidebar': 'oklch(0.205 0 0)',
    '--sidebar-foreground': 'oklch(0.985 0 0)',
    '--sidebar-primary': 'oklch(0.623 0.214 259.815)',
    '--sidebar-primary-foreground': 'oklch(0.97 0.014 254.604)',
    '--sidebar-accent': 'oklch(0.269 0 0)',
    '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
    '--sidebar-border': 'oklch(1 0 0 / 10%)',
    '--sidebar-ring': 'oklch(0.556 0 0)',
    '--header': 'oklch(0.205 0 0)',
    '--header-foreground': 'oklch(0.985 0 0)',
    '--header-border': 'oklch(1 0 0 / 10%)',
    '--table-header': 'oklch(0.269 0 0)',
    '--table-header-foreground': 'oklch(0.708 0 0)',
    '--table-row': 'oklch(0.205 0 0)',
    '--table-row-foreground': 'oklch(0.985 0 0)',
    '--table-row-hover': 'oklch(0.25 0 0)',
    '--table-row-selected': 'oklch(0.3 0.04 264.376)',
    '--table-row-stripe': 'oklch(0.22 0 0)',
    '--table-border': 'oklch(1 0 0 / 10%)',
    '--table-font-size': '0.75rem',
    '--table-row-height': '1.75rem',
    '--radius': '0.45rem',
  },
}
